### ISSUE TITLE
🔧 [FIX] 7.11 모각코 이슈 목록

### ISSUE THREAD

**Issue by chamm99** [LikeLion12-Team1/Team1-Back#33]
## 📝 개요
- 7.11 모각코 이슈 목록

## ✔️ To-Do
- [x] 챌린지 조회 Dto 속성에 챌린지 이름 추가
- [x] 크루 생성 500 에러
- [x] 신고 방식 수정
- [x] 크루 게시글 목록 조회 점검
- [x] 크루 생성 이미지 업로드 에러 해결
- [x] 특정 크루 리스트 안에 리스트 리스폰스 해결
- [x] 특정 챌린지 참여중인 크루 목록 API 추가
- [x] 특정 크루 커뮤니티 게시글 목록 조회 API 추가
- [x] 플랜트 화면 조회 보유 토큰 반환 속성 추가
- [x] 특정 게시글 조회 시 댓글 목록, 댓글 작성자 정보 반환 추가
- [x] 게시글 사진 안넣고 작성 케이스 수정
- [x] 마이 페이지 관련 조회 오류 수정
- [x] 게시글 등록 반환 방식 수정
- [x] 식물 해금 오류 수정
