### ISSUE TITLE
🔧 [FIX] 최종 수정 목록

### ISSUE THREAD

**Issue by chamm99** [LikeLion12-Team1/Team1-Back#48]
## 📝 개요
- 최종 API 수정 목록

## ✔️ To-Do
- [x] 게시글 작성시 crew post 연관관계 추가
- [x] DB 속성 점검, 설정 (default 값 부여되어야 하는 케이스)
- [ ] S3 더미 데이터 삭제, 이미지 업로드시 기존 이미지 삭제처리, 기본 이미지 업로드
- [ ]
