### ISSUE TITLE
✨ [FEATURE] 프로필, 마이 페이지 관련 기능

### ISSUE THREAD

**Issue by chamm99** [LikeLion12-Team1/Team1-Back#5]
## 📝 개요
- User 관련 기능 추가

## ✔️ To-Do 
- 프로필
- [x] 프로필 조회
- [x] 닉네임 수정 (중복 확인 필요)
- [x] 프로필 사진 수정
- [x] 활동 지역 수정
- [x] 소속 크루 목록 조회
- [x] 소속 크루 탈퇴
- 마이 페이지
- [x] 소속 크루 목록 조회
- [x] 챌린지 목록 조회
- [x] 달성한 챌린지 보상 획득
- 관리자 페이지
- [x] 관리자 MyCrew 페이지 조회
- [x] MyCrew / Member페이지에서 멤버 삭제 기능 (권한 방식)
- [x] MyCrew / Community 페이지에서 크루원들이 올린 챌린지 인증, 신고된 글 삭제 기능
