### ISSUE TITLE
✨ [FEATURE] 식물 관련 기능

### ISSUE THREAD

**Issue by chamm99** [LikeLion12-Team1/Team1-Back#7]
## 📝 개요
- 식물 관련 기능 추가

## ✔️ To-Do
- [x]  사용자가 해금한 식물 목록 조회 
- [x] 식물 체크해서 사용자 대표 식물로 설정
- [x] 챌린지 달성 확인 후 사용자 토큰 수령
- [x] 토큰 지불하여 식물 해금
