### ISSUE TITLE
✨ [FEATURE] 크루 관련 기능

### ISSUE THREAD

**Issue by chamm99** [LikeLion12-Team1/Team1-Back#8]
## 📝 개요
- 크루 관련 기능 추가

## ✔️ To-Do
- 크루 생성
- [x] 크루 이미지 설정
- [x] 크루 이름 설정
- [x] 크루 이름 중복 확인
- [x] 크루 활동 지역 설정
- [x] 크루 스포츠 타입 설정
- 크루 서치 
- [x] 크루 목록 전체 조회 (크루 이미지, 크루명, 지역, 스포츠타입, 페이지네이션 8개씩)
- [x] 크루 목록 지역별 조회
- [x] 크루 목록 스포츠타입별 조회
- 크루 정보
- [x] 특정 크루 정보 조회 (크루 커뮤니티 이미지 목록, 크루명, 가입 인원수, 진행한 챌린지 목록, 크루 개설일)
- [x] 가입 신청 기능
- 크루 플랜트
- [x] 크루 플랜트 조회 (크루 구성원 닉네임, 대표 식물)
- 크루 커뮤니티
- [x] 게시글 생성
- [x] 게시글 목록 전체 조회 (작성자, 마지막 수정 시간, 사용자가 좋아요 눌렀는지 여부, 타입 - 일상 인증, 무한 스크롤)
- [x] 게시글 타입별 조회 (일상, 인증)
- [x] 게시글 댓글 목록 조회 (댓글 작성자, 댓글 내용)
- [x] 신고하기
