### ISSUE TITLE
✨ [FEATURE] 챌린지 관련 기능

### ISSUE THREAD

**Issue by chamm99** [LikeLion12-Team1/Team1-Back#9]
## 📝 개요
- 챌린지 관련 기능 추가

## ✔️ To-Do
- 챌린지 조회
- [x] 챌린지 목록 전체 조회 (무한 스크롤, 참여 인원수, 크루 사진, 지역)
- [x] 챌린지 목록 지역별 조회
- [x] 챌린지 목록 스포츠 타입별 조회
- [x] 챌린지 개별 정보 조회 (챌린지 기간, 챌린지 정보 ex) 10 km(6.2 mi) 달리기, 참여중인 크루 수)
